# name: Add Domains on PR Open
# on:
#   pull_request:
#     types: [opened]
# jobs:
#   add-domains:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Add DNS Records and Custom Domains
#         run: node addDomains.js
#         env:
#           CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
#           GITHUB_PR_NUMBER: ${{ github.event.number }}
#           DOMAIN: ${{ secrets.DOMAIN }}
#           BRANCH_NAME: ${{ github.head_ref }}
