# name: Update Cloudflare DNS for PR Previews

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     # !!! remove "main" branch  (exclude)

# jobs:
#   update-dns:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "18"
#           cache: "npm"

#       - name: Install Axios
#         run: npm install axios

#       - name: Add / Update / Delete DNS Record
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
#           BRANCH_NAME: ${{ github.head_ref }}
#           DOMAIN: ${{ secrets.DOMAIN }}
#           GITHUB_PR_NUMBER: ${{ github.event.number }}
#         run: node .github/scripts/dns2.js
