name: Update Cloudflare DNS for PR Previews

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  update-dns:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Axios
        run: npm install axios

      - name: Update DNS Record
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: node .github/scripts/add_remove_dns.js
